# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'newStore' do  

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for newStore
  pod 'ColorMatchTabs', '~> 2.0'
  pod 'Money'
  pod 'Segmentio', '~> 2.1'
end


